
USE MERCADO_01
--TELEFONE
INSERT INTO TBL_TELEFONE(TEL_DDD,TEL_FIXO,TEL_CELULAR,TEL_OPERADORA)VALUES('011','84597284','974556230','CLARO') 
INSERT INTO TBL_TELEFONE(TEL_DDD,TEL_FIXO,TEL_CELULAR,TEL_OPERADORA)VALUES('011','33397284','964556232','TIM')
INSERT INTO TBL_TELEFONE(TEL_DDD,TEL_FIXO,TEL_CELULAR,TEL_OPERADORA)VALUES('011','83397287','944556231','CLARO')
INSERT INTO TBL_TELEFONE(TEL_DDD,TEL_FIXO,TEL_CELULAR,TEL_OPERADORA)VALUES('011','83397288','944556232','NEXTEL')
INSERT INTO TBL_TELEFONE(TEL_DDD,TEL_FIXO,TEL_CELULAR,TEL_OPERADORA)VALUES('011','77397288','664556232','OI')
--SUB_CATEGORIA
INSERT INTO TBL_SUB_CATEGORIA(SUB_CAT_TIPO) VALUES('INFORMÁTICA')
INSERT INTO TBL_SUB_CATEGORIA(SUB_CAT_TIPO) VALUES('MATERIAL ESCOLAR')
INSERT INTO TBL_SUB_CATEGORIA(SUB_CAT_TIPO) VALUES('REMÉDIO')
INSERT INTO TBL_SUB_CATEGORIA(SUB_CAT_TIPO) VALUES('BJUTERIA')
INSERT INTO TBL_SUB_CATEGORIA(SUB_CAT_TIPO) VALUES('CÓSMETICO')
INSERT INTO TBL_SUB_CATEGORIA(SUB_CAT_TIPO) VALUES('BRINQUEDOS')
INSERT INTO TBL_SUB_CATEGORIA(SUB_CAT_TIPO) VALUES('PAPELÁRIA')
INSERT INTO TBL_SUB_CATEGORIA(SUB_CAT_TIPO) VALUES('HIGIENE')
SELECT * FROM TBL_SUB_CATEGORIA

--PRODUTO
INSERT INTO TBL_PRODUTO(PROD_COD,PROD_NOME,PROD_MARCA,PROD_QTD,PROD_QTD_MIN,PROD_VALOR,PROD_VALOR_VENDA,SUB_CAT_ID,PROD_STATUS)
VALUES ('000123214033','ESTOJO BATMAN','FABER CASTEL',20,20,8.60,15.00,2,'ATIVO')

INSERT INTO TBL_PRODUTO(PROD_COD,PROD_NOME,PROD_MARCA,PROD_QTD,PROD_QTD_MIN,PROD_VALOR,PROD_VALOR_VENDA,SUB_CAT_ID,PROD_STATUS)
VALUES ('800123214030','TECLADO','BRIGHT',20,20,15.00,20.00,1,'ATIVO')

INSERT INTO TBL_PRODUTO(PROD_COD,PROD_NOME,PROD_MARCA,PROD_QTD,PROD_QTD_MIN,PROD_VALOR,PROD_VALOR_VENDA,SUB_CAT_ID,PROD_STATUS)
VALUES ('100123214999','PERFUME ESSENCIAL','NATURA',30,20,50.60,80.00,5,'ATIVO')

SELECT * FROM TBL_PRODUTO
--FORNECEDOR


INSERT INTO TBL_FORNECEDOR(FOR_NOME,FOR_CNPJ,FOR_NOME_FANT,FOR_EMAIL,FOR_DESC)
VALUES(NULL,NULL,NULL,NULL,NULL)

INSERT INTO TBL_FORNECEDOR(TEL_ID,FOR_NOME,FOR_CNPJ,FOR_NOME_FANT,FOR_EMAIL,FOR_DESC,FOR_STATUS)
VALUES(1,'MATIAS CAMPOS','22365984523622','EXTRA','extra@hotmail.com','Mercado','ATIVO')

INSERT INTO TBL_FORNECEDOR(TEL_ID,FOR_NOME,FOR_CNPJ,FOR_NOME_FANT,FOR_EMAIL,FOR_DESC,FOR_STATUS)
VALUES(2,'MARIO SUZANO','32365984523333','IMPORTADOS LTDA','importltda@hotmail.com','Loja de importados','ATIVO')

INSERT INTO TBL_FORNECEDOR(TEL_ID,FOR_NOME,FOR_CNPJ,FOR_NOME_FANT,FOR_EMAIL,FOR_DESC,FOR_STATUS)
VALUES(3,'LUIZA MARTINS SILVA','12365984523657','NATURA','natura@hotmail.com','Loja de cósmeticos','ATIVO')

SELECT * FROM TBL_FORNECEDOR

INSERT INTO TBL_PROD_FORN(PROD_ID, FOR_ID)VALUES(1,2)
INSERT INTO TBL_PROD_FORN(PROD_ID, FOR_ID)VALUES(2,3)
INSERT INTO TBL_PROD_FORN(PROD_ID, FOR_ID)VALUES(3,4)
SELECT * FROM TBL_PROD_FORN

--INSERT INTO TBL_ENDERECO(END_BAIRRO,END_RUA,END_NUMERO,END_CEP) VALUES (NULL,NULL,NULL,NULL)
INSERT INTO TBL_ENDERECO(END_BAIRRO,END_RUA,END_NUMERO,END_CEP) VALUES ('Santana','Marechal Osório',14,'05037030')
INSERT INTO TBL_ENDERECO(END_BAIRRO,END_RUA,END_NUMERO,END_CEP) VALUES ('Lapa','Cléria',1001,'35037050')
INSERT INTO TBL_ENDERECO(END_BAIRRO,END_RUA,END_NUMERO,END_CEP) VALUES (' JD Clara','Maria',200,'35037060')
INSERT INTO TBL_ENDERECO(END_BAIRRO,END_RUA,END_NUMERO,END_CEP) VALUES (' Água Branca','Capitão Franfisco',38,'05037020')
SELECT * FROM TBL_ENDERECO

INSERT INTO TBL_FOR_END (FOR_ID,END_ID) VALUES (2,2)
INSERT INTO TBL_FOR_END (FOR_ID,END_ID) VALUES (3,3)
INSERT INTO TBL_FOR_END (FOR_ID,END_ID) VALUES (4,4)
SELECT * FROM TBL_FOR_END

INSERT INTO TBL_CLIENTE(CLI_NOME,CLI_DIVIDA) VALUES ('CLIENTE-1',0.00)
INSERT INTO TBL_CLIENTE(CLI_NOME,TEL_ID,CLI_RG,CLI_CPF,CLI_DIVIDA,CLI_STATUS) VALUES ('Jean Francisco',5,'756325698','36256342522',0.00,'ATIVO')
INSERT INTO TBL_CLI_END(CLI_ID,END_ID) VALUES (2,4)
SELECT * FROM TBL_CLIENTE
SELECT * FROM TBL_CLI_END


INSERT INTO TBL_LOGIN(LOG_LOGIN, LOG_SENHA) VALUES ('admin123', 'admin123');