USE MERCADO_01

SELECT * FROM TBL_PRODUTO
SELECT * FROM TBL_VENDA
SELECT * FROM TBL_ITEM_VENDA
SELECT * FROM TBL_PROD_FORN
SELECT * FROM TBL_SUB_CATEGORIA
<<<<<<< HEAD
SELECT * FROM TBL_LOGIN
=======
SELECT * FROM TBL_FOTO
SELECT * FROM TBL_FORNECEDOR
SELECT * FROM TBL_ENDERECO
SELECT * FROM TBL_TELEFONE
SELECT * FROM TBL_FOR_END
SELECT * FROM TBL_CLIENTE ORDER BY CLI_NOME ASC

UPDATE TBL_PRODUTO SET PROD_QTD = 5 WHERE PROD_ID = 1

SELECT CLI_ID, CLI_NOME FROM TBL_CLIENTE WHERE CLI_ID > 1 ORDER BY CLI_NOME ASC